package cn.com.qytx.cbb.autoCreateEntity.controller;

import java.io.File;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.Calendar;

import javax.annotation.Resource;

import org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import cn.com.qytx.cbb.autoEntity.service.AutoCreateEntityService;
import cn.com.qytx.cbb.autoEntity.service.AutoCreateTableService;
import cn.com.qytx.cbb.autoEntity.service.CommonService;
import cn.com.qytx.platform.base.action.BaseControllerSupport;
import cn.com.qytx.platform.base.scan.ContainerEntityManagerFactoryBean;

/**
 * @author jiayongqiang
 *
 */
@Controller
@RequestMapping("/testAutoEntity")
public class TestAutoEntityController extends BaseControllerSupport {

	@Resource
	private AutoCreateTableService tableService;
	@Resource
	private AutoCreateEntityService entityService;
	@Resource
	private CommonService commonService;
	@Resource
	private ContainerEntityManagerFactoryBean containerEntityManagerFactoryBean;
	
	@ResponseBody
	@RequestMapping("/test.c")
	public void test() throws SecurityException, NoSuchMethodException, IllegalArgumentException, IllegalAccessException, InvocationTargetException, InstantiationException{
		//第一步,创建数据库
		tableService.createTable(null);
				
		//第二步,创建Java文件
		File f = entityService.createEntity(null);
				
		//第三部，编译java文件，并加载到JVM中
		Class c = entityService.compileFile(f);
		Method m = null;
		m = c.getMethod("hello", null);
		m.invoke(c.newInstance(), null);
		
		//第四布，将该class放入jpa容器中
		long l = Calendar.getInstance().getTimeInMillis();
		containerEntityManagerFactoryBean.setScanPackages("autoGenerateDomain");
		containerEntityManagerFactoryBean.afterPropertiesSet();
		long l2 = Calendar.getInstance().getTimeInMillis();
		System.out.println(l2-l);
		
		Object o = commonService.findOne(c, 1);
		Method m2 = c.getMethod("getCityName");
		Object r = m2.invoke(o, null);
		System.out.println(r);
		LocalContainerEntityManagerFactoryBean bean = null;
//		return SUCCESS();
	}
}
