package autoGenerateDomain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="Citys")
public class Citys {
	@Id
    @Column(name = "Number")
    @GeneratedValue(strategy = GenerationType.AUTO)
	private Integer number;
	
	@Column(name="CityName")
	private String cityName;
	
	@Column(name="PhoneNO")
	private String PhoneNO;
	
	@Column(name="BOSSNO")
	private String BOSSNO;

	public Integer getNumber() {
		return number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getPhoneNO() {
		return PhoneNO;
	}

	public void setPhoneNO(String phoneNO) {
		PhoneNO = phoneNO;
	}

	public String getBOSSNO() {
		return BOSSNO;
	}

	public void setBOSSNO(String bOSSNO) {
		BOSSNO = bOSSNO;
	}
	
	public void hello(){
		System.out.println("hello,world");
	}
}
